# Generated by Django 6.0.8 on 2026-08-06 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="fullname",
        ),
    ]
