# Generated by Django 6.0.8 on 2026-08-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_remove_user_fullname"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="fullname",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="نام کامل"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_admin",
            field=models.BooleanField(default=False, verbose_name="ادمین"),
        ),
    ]
