# Generated by Django 6.0.8 on 2026-08-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_user_fullname_alter_user_is_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True, max_length=10, null=True, unique=True, verbose_name="شماره"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True, max_length=55, null=True, verbose_name="ایمیل"
            ),
        ),
    ]
