# Generated by Django 6.0.8 on 2026-08-08 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_user_phone_alter_user_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="phone",
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=55, null=True, unique=True, verbose_name="ایمیل"
            ),
        ),
    ]
