# Generated by Django 6.0.8 on 2026-08-08 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_remove_user_phone_alter_user_email"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "کاربر", "verbose_name_plural": "کاربرها"},
        ),
    ]
