# Generated by Django 6.0.8 on 2026-08-10 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0007_otp_alter_user_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailOTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("otp", models.CharField(max_length=6)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Otp",
        ),
    ]
