# Generated by Django 6.0.8 on 2026-08-10 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0008_emailotp_delete_otp"),
    ]

    operations = [
        migrations.RenameField(
            model_name="emailotp",
            old_name="otp",
            new_name="code",
        ),
        migrations.AddField(
            model_name="emailotp",
            name="is_used",
            field=models.BooleanField(default=False),
        ),
    ]
