# Generated by Django 6.0.8 on 2026-08-11 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0009_rename_otp_emailotp_code_emailotp_is_used"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_admin",
            field=models.BooleanField(default=True, verbose_name="ادمین"),
        ),
    ]
