# Generated by Django 6.0.8 on 2026-08-11 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0010_alter_user_is_admin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailotp",
            name="code",
            field=models.CharField(max_length=6, verbose_name="کد یکبار مصرف"),
        ),
        migrations.AlterField(
            model_name="emailotp",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="ایمیل شما"),
        ),
        migrations.AlterField(
            model_name="emailotp",
            name="is_used",
            field=models.BooleanField(default=True),
        ),
    ]
