# Generated by Django 6.0.8 on 2026-08-16 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0011_alter_emailotp_code_alter_emailotp_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailotp",
            name="is_used",
            field=models.BooleanField(default=False),
        ),
    ]
